//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR6_MDK01_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logined
    {
        public int IdUser { get; set; }
        public string LoginUser { get; set; }
        public int PasswordUser { get; set; }
        public int IdRole { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Students Students { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
