//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR6_MDK01_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkStudents
    {
        public int IdEntry { get; set; }
        public int IdStudent { get; set; }
        public int IdDiscipline { get; set; }
        public int IdTypeOfReporting { get; set; }
        public System.DateTime DateReporting { get; set; }
        public int General { get; set; }
        public int IdMark { get; set; }
        public int IdTeacher { get; set; }
    
        public virtual Disciplines Disciplines { get; set; }
        public virtual Marks Marks { get; set; }
        public virtual Students Students { get; set; }
        public virtual Teachers Teachers { get; set; }
        public virtual TypesOfReporting TypesOfReporting { get; set; }
    }
}
