//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR6_MDK01_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photos
    {
        public int IdPhoto { get; set; }
        public int IdUser { get; set; }
        public string PhotoPath { get; set; }
        public byte[] PhotoBinary { get; set; }
        public Nullable<bool> MainPhoto { get; set; }
    
        public virtual Logined Logined { get; set; }
    }
}
