//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR6_MDK01_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyPlan
    {
        public int IdEntry { get; set; }
        public int IdGroup { get; set; }
        public int IdDiscipline { get; set; }
        public int Lecture { get; set; }
        public int Practice { get; set; }
        public int IdTypeOfReporting { get; set; }
        public double General { get; set; }
        public int IdTeacher { get; set; }
    
        public virtual Disciplines Disciplines { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Teachers Teachers { get; set; }
        public virtual TypesOfReporting TypesOfReporting { get; set; }
    }
}
