//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR6_MDK01_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teachers()
        {
            this.Lessons = new HashSet<Lessons>();
            this.MarkStudents = new HashSet<MarkStudents>();
            this.StudyPlan = new HashSet<StudyPlan>();
        }
    
        public int IdTeacher { get; set; }
        public string Surname { get; set; }
        public string NameTeacher { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime Birthday { get; set; }
        public int IdGender { get; set; }
        public int IdDepartment { get; set; }
        public int IdTitle { get; set; }
        public double Bet { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual Genders Genders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lessons> Lessons { get; set; }
        public virtual Logined Logined { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarkStudents> MarkStudents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudyPlan> StudyPlan { get; set; }
        public virtual Titles Titles { get; set; }
    }
}
